#pragma once
#include "Cinnamon/include/Core/Core.h"

namespace Cinnamon {
#define DEFINE_KEY(name, code) name = code
	using KeyCode = uint16_t;

	enum class EKeyState : uint8_t
	{
		Released	= BIT(1),
		Pressed		= BIT(2),
		Repeat		= BIT(3)
	};

	enum class Key : KeyCode
	{
#ifdef CIN_PLATFORM_WINDOWS
		DEFINE_KEY(Backspace, 0x08),
		DEFINE_KEY(Enter, 0x0D),
		DEFINE_KEY(Tab, 0x09),
		DEFINE_KEY(Shift, 0x10),
		DEFINE_KEY(Control, 0x11),

		DEFINE_KEY(Pause, 0x13),
		DEFINE_KEY(Capital, 0x14),

		DEFINE_KEY(Escape, 0x1B),

		DEFINE_KEY(Convert, 0x1C),
		DEFINE_KEY(Nonconvert, 0x1D),
		DEFINE_KEY(Accept, 0x1E),
		DEFINE_KEY(Modechange, 0x1F),

		DEFINE_KEY(Space, 0x20),
		DEFINE_KEY(Prior, 0x21),
		DEFINE_KEY(Next, 0x22),
		DEFINE_KEY(End, 0x23),
		DEFINE_KEY(Home, 0x24),
		DEFINE_KEY(Left, 0x25),
		DEFINE_KEY(Up, 0x26),
		DEFINE_KEY(Right, 0x27),
		DEFINE_KEY(Down, 0x28),
		DEFINE_KEY(Select, 0x29),
		DEFINE_KEY(Print, 0x2A),
		DEFINE_KEY(Execute, 0x2B),
		DEFINE_KEY(Snapshot, 0x2C),
		DEFINE_KEY(Insert, 0x2D),
		DEFINE_KEY(Delete, 0x2E),
		DEFINE_KEY(Help, 0x2F),

		DEFINE_KEY(A, 0x41),
		DEFINE_KEY(B, 0x42),
		DEFINE_KEY(C, 0x43),
		DEFINE_KEY(D, 0x44),
		DEFINE_KEY(E, 0x45),
		DEFINE_KEY(F, 0x46),
		DEFINE_KEY(G, 0x47),
		DEFINE_KEY(H, 0x48),
		DEFINE_KEY(I, 0x49),
		DEFINE_KEY(J, 0x4A),
		DEFINE_KEY(K, 0x4B),
		DEFINE_KEY(L, 0x4C),
		DEFINE_KEY(M, 0x4D),
		DEFINE_KEY(N, 0x4E),
		DEFINE_KEY(O, 0x4F),
		DEFINE_KEY(P, 0x50),
		DEFINE_KEY(Q, 0x51),
		DEFINE_KEY(R, 0x52),
		DEFINE_KEY(S, 0x53),
		DEFINE_KEY(T, 0x54),
		DEFINE_KEY(U, 0x55),
		DEFINE_KEY(V, 0x56),
		DEFINE_KEY(W, 0x57),
		DEFINE_KEY(X, 0x58),
		DEFINE_KEY(Y, 0x59),
		DEFINE_KEY(Z, 0x5A),

		DEFINE_KEY(LeftWindows, 0x5B),
		DEFINE_KEY(RightWindows, 0x5C),
		DEFINE_KEY(Applications, 0x5D),

		DEFINE_KEY(Sleep, 0x5F),

		DEFINE_KEY(NUMPAD0, 0x60),
		DEFINE_KEY(NUMPAD1, 0x61),
		DEFINE_KEY(NUMPAD2, 0x62),
		DEFINE_KEY(NUMPAD3, 0x63),
		DEFINE_KEY(NUMPAD4, 0x64),
		DEFINE_KEY(NUMPAD5, 0x65),
		DEFINE_KEY(NUMPAD6, 0x66),
		DEFINE_KEY(NUMPAD7, 0x67),
		DEFINE_KEY(NUMPAD8, 0x68),
		DEFINE_KEY(NUMPAD9, 0x69),
		DEFINE_KEY(Multiply, 0x6A),
		DEFINE_KEY(Add, 0x6B),
		DEFINE_KEY(Separator, 0x6C),
		DEFINE_KEY(Subtract, 0x6D),
		DEFINE_KEY(Decimal, 0x6E),
		DEFINE_KEY(Divide, 0x6F),
		DEFINE_KEY(F1, 0x70),
		DEFINE_KEY(F2, 0x71),
		DEFINE_KEY(F3, 0x72),
		DEFINE_KEY(F4, 0x73),
		DEFINE_KEY(F5, 0x74),
		DEFINE_KEY(F6, 0x75),
		DEFINE_KEY(F7, 0x76),
		DEFINE_KEY(F8, 0x77),
		DEFINE_KEY(F9, 0x78),
		DEFINE_KEY(F10, 0x79),
		DEFINE_KEY(F11, 0x7A),
		DEFINE_KEY(F12, 0x7B),
		DEFINE_KEY(F13, 0x7C),
		DEFINE_KEY(F14, 0x7D),
		DEFINE_KEY(F15, 0x7E),
		DEFINE_KEY(F16, 0x7F),
		DEFINE_KEY(F17, 0x80),
		DEFINE_KEY(F18, 0x81),
		DEFINE_KEY(F19, 0x82),
		DEFINE_KEY(F20, 0x83),
		DEFINE_KEY(F21, 0x84),
		DEFINE_KEY(F22, 0x85),
		DEFINE_KEY(F23, 0x86),
		DEFINE_KEY(F24, 0x87),

		DEFINE_KEY(Numlock, 0x90),
		DEFINE_KEY(Scroll, 0x91),

		DEFINE_KEY(NUMPAD_EQUAL, 0x92),

		DEFINE_KEY(LeftShift, 0xA0),
		DEFINE_KEY(RightShift, 0xA1),
		DEFINE_KEY(LeftControl, 0xA2),
		DEFINE_KEY(RightControl, 0xA3),
		DEFINE_KEY(LeftMenu, 0xA4),
		DEFINE_KEY(RightMenu, 0xA5),

		DEFINE_KEY(SemiColon, 0xBA),
		DEFINE_KEY(Plus, 0xBB),
		DEFINE_KEY(Comma, 0xBC),
		DEFINE_KEY(Minus, 0xBD),
		DEFINE_KEY(Period, 0xBE),
		DEFINE_KEY(Slash, 0xBF),
		DEFINE_KEY(Grave, 0xC0),
#elif defined CIN_PLATFORM_LINUX
#include <linux/input-event-codes.h>

		DEFINE_KEY(Backspace, KEY_BACKSPACE),
		DEFINE_KEY(Enter, KEY_ENTER),
		DEFINE_KEY(Tab, KEY_TAB),
		DEFINE_KEY(Shift, KEY_LEFTSHIFT),
		DEFINE_KEY(Control, KEY_LEFTCTRL),

		DEFINE_KEY(Pause, KEY_PAUSE),
		DEFINE_KEY(Capital, KEY_CAPSLOCK),

		DEFINE_KEY(Escape, KEY_ESC),

		/*
		DEFINE_KEY(Convert, ),
		DEFINE_KEY(Nonconvert, ),
		DEFINE_KEY(Accept, ),
		DEFINE_KEY(Modechange, ),
		*/

		DEFINE_KEY(Space, KEY_SPACE),
		DEFINE_KEY(Prior, KEY_PREVIOUS),
		DEFINE_KEY(Next, KEY_NEXT),
		DEFINE_KEY(End, KEY_END),
		DEFINE_KEY(Home, KEY_HOME),
		DEFINE_KEY(Left, KEY_LEFT),
		DEFINE_KEY(Up, KEY_UP),
		DEFINE_KEY(Right, KEY_RIGHT),
		DEFINE_KEY(Down, KEY_DOWN),
		DEFINE_KEY(Select, KEY_SELECT),
		DEFINE_KEY(Print, KEY_PRINT),
		/* DEFINE_KEY(Execute), */
		/* DEFINE_KEY(Snapshot,), */
		DEFINE_KEY(Insert, KEY_INSERT),
		DEFINE_KEY(Delete, KEY_DELETE),
		DEFINE_KEY(Help, KEY_HELP),

		DEFINE_KEY(A, KEY_A),
		DEFINE_KEY(B, KEY_B),
		DEFINE_KEY(C, KEY_C),
		DEFINE_KEY(D, KEY_D),
		DEFINE_KEY(E, KEY_E),
		DEFINE_KEY(F, KEY_F),
		DEFINE_KEY(G, KEY_G),
		DEFINE_KEY(H, KEY_H),
		DEFINE_KEY(I, KEY_I),
		DEFINE_KEY(J, KEY_J),
		DEFINE_KEY(K, KEY_K),
		DEFINE_KEY(L, KEY_L),
		DEFINE_KEY(M, KEY_M),
		DEFINE_KEY(N, KEY_N),
		DEFINE_KEY(O, KEY_O),
		DEFINE_KEY(P, KEY_P),
		DEFINE_KEY(Q, KEY_Q),
		DEFINE_KEY(R, KEY_R),
		DEFINE_KEY(S, KEY_S),
		DEFINE_KEY(T, KEY_T),
		DEFINE_KEY(U, KEY_U),
		DEFINE_KEY(V, KEY_V),
		DEFINE_KEY(W, KEY_W),
		DEFINE_KEY(X, KEY_X),
		DEFINE_KEY(Y, KEY_Y),
		DEFINE_KEY(Z, KEY_Z),

		/*
		DEFINE_KEY(LeftWindows, ),
		DEFINE_KEY(RightWindows, ),
		DEFINE_KEY(Applications, KEY_APPSELECT),
		*/

		DEFINE_KEY(Sleep, KEY_SLEEP),

		DEFINE_KEY(NUMPAD0, KEY_KP0),
		DEFINE_KEY(NUMPAD1, KEY_KP1),
		DEFINE_KEY(NUMPAD2, KEY_KP2),
		DEFINE_KEY(NUMPAD3, KEY_KP3),
		DEFINE_KEY(NUMPAD4, KEY_KP4),
		DEFINE_KEY(NUMPAD5, KEY_KP5),
		DEFINE_KEY(NUMPAD6, KEY_KP6),
		DEFINE_KEY(NUMPAD7, KEY_KP7),
		DEFINE_KEY(NUMPAD8, KEY_KP8),
		DEFINE_KEY(NUMPAD9, KEY_KP9),

		DEFINE_KEY(Multiply, KEY_KPASTERISK),
		DEFINE_KEY(Add, KEY_KPPLUS),
		/* DEFINE_KEY(Separator, ), */
		DEFINE_KEY(Subtract, KEY_KPMINUS),
		/* DEFINE_KEY(Decimal, ), */
		DEFINE_KEY(Divide, KEY_KPSLASH),

		DEFINE_KEY(F1, KEY_F1),
		DEFINE_KEY(F2, KEY_F2),
		DEFINE_KEY(F3, KEY_F3),
		DEFINE_KEY(F4, KEY_F4),
		DEFINE_KEY(F5, KEY_F5),
		DEFINE_KEY(F6, KEY_F6),
		DEFINE_KEY(F7, KEY_F7),
		DEFINE_KEY(F8, KEY_F8),
		DEFINE_KEY(F9, KEY_F9),
		DEFINE_KEY(F10, KEY_F10),
		DEFINE_KEY(F11, KEY_F11),
		DEFINE_KEY(F12, KEY_F12),
		DEFINE_KEY(F13, KEY_F13),
		DEFINE_KEY(F14, KEY_F14),
		DEFINE_KEY(F15, KEY_F15),
		DEFINE_KEY(F16, KEY_F16),
		DEFINE_KEY(F17, KEY_F17),
		DEFINE_KEY(F18, KEY_F18),
		DEFINE_KEY(F19, KEY_F19),
		DEFINE_KEY(F20, KEY_F20),
		DEFINE_KEY(F21, KEY_F21),
		DEFINE_KEY(F22, KEY_F22),
		DEFINE_KEY(F23, KEY_F23),
		DEFINE_KEY(F24, KEY_F24),

		DEFINE_KEY(Numlock, KEY_NUMLOCK),
		DEFINE_KEY(Scroll, KEY_SCROLLLOCK),

		DEFINE_KEY(NUMPAD_EQUAL, KEY_KPEQUAL),

		DEFINE_KEY(LeftShift, KEY_LEFTSHIFT),
		DEFINE_KEY(RightShift, KEY_RIGHTSHIFT),
		DEFINE_KEY(LeftControl, KEY_LEFTCTRL),
		DEFINE_KEY(RightControl, KEY_RIGHTCTRL),

		/*
		DEFINE_KEY(LeftMenu, ),
		DEFINE_KEY(RightMenu, ),
		*/

		DEFINE_KEY(SemiColon, KEY_SEMICOLON),
		/* DEFINE_KEY(Plus,), */
		DEFINE_KEY(Comma, KEY_COMMA),
		DEFINE_KEY(Minus, KEY_MINUS),
		DEFINE_KEY(Period, KEY_DOT),
		DEFINE_KEY(Slash, KEY_SLASH),
		DEFINE_KEY(Grave, KEY_GRAVE),

#elif defined CIN_PLATFORM_APPLE
#endif
		KeysEnd,
	};
}